CREATE TABLE IF NOT EXISTS professors (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS students (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	teacher_id INTEGER NOT NULL,
	monthly REAL NOT NULL,
	scholar BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS payments (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	date_payment DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	student_id INTEGER NOT NULL,
	teacher_id INTEGER NOT NULL,
	month INTEGER NOT NULL,
	year INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS expenses (
	description TEXT NOT NULL UNIQUE,
	value REAL NOT NULL DEFAULT 0
);
