CREATE TABLE IF NOT EXISTS professors (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS students (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	teacher_id INTEGER NOT NULL,
	monthly REAL NOT NULL,
	scholar BOOLEAN NOT NULL DEFAULT FALSE
);
